// app/api/products/route.js
export async function GET() {
    const products = [
        {
          id: 1,
          name: "Organic Himsagar Mango",
          description: "Premium quality Himsagar mangoes grown organically in Chapai Nawabganj.",
          price: 450,
          originalPrice: 550,
          images: [
            "/images/products/himsagar-1.webp",
            "/images/products/himsagar-2.webp",
            "/images/products/himsagar-3.webp",
          ],
          rating: 4.8,
          reviews: 124,
          discount: "18% OFF",
          isNew: true,
          stock: 15,
          benefits: [
            "100% Organic Certification",
            "No Artificial Ripening",
            "Direct from Farm to Doorstep",
            "Rich in Vitamins A & C",
          ],
          variety: "Himsagar",
          slug: "organic-himsagar-mango",
        },
        {
          id: 2,
          name: "Premium Langra Mango",
          description: "Authentic Langra mangoes from Rajshahi with unmatched sweetness.",
          price: 400,
          originalPrice: 500,
          images: [
            "/images/products/langra-1.webp",
            "/images/products/langra-2.webp",
            "/images/products/langra-3.webp",
          ],
          rating: 4.7,
          reviews: 110,
          discount: "20% OFF",
          isNew: true,
          stock: 20,
          benefits: [
            "Naturally Ripened",
            "High Sugar Content",
            "Farm to Table Fresh",
            "Rich Aroma and Taste",
          ],
          variety: "Langra",
          slug: "premium-langra-mango",
        },
        {
          id: 3,
          name: "Organic Amrapali Mango",
          description: "Juicy Amrapali mangoes with a perfect balance of sweetness and acidity.",
          price: 380,
          originalPrice: 460,
          images: [
            "/images/products/amrapali-1.webp",
            "/images/products/amrapali-2.webp",
            "/images/products/amrapali-3.webp",
          ],
          rating: 4.6,
          reviews: 95,
          discount: "17% OFF",
          isNew: false,
          stock: 30,
          benefits: [
            "Long Shelf Life",
            "Perfect for Juices",
            "Farm Grown & Organic",
            "Low Fiber, Smooth Texture",
          ],
          variety: "Amrapali",
          slug: "organic-amrapali-mango",
        },
        {
          id: 4,
          name: "Fresh Fazli Mango",
          description: "Large, fibrous, and juicy Fazli mangoes ideal for pickles and pulps.",
          price: 420,
          originalPrice: 520,
          images: [
            "/images/products/fazli-1.webp",
            "/images/products/fazli-2.webp",
            "/images/products/fazli-3.webp",
          ],
          rating: 4.5,
          reviews: 80,
          discount: "19% OFF",
          isNew: false,
          stock: 18,
          benefits: [
            "Best for Pickles",
            "Fiber Rich",
            "High Yield per Mango",
            "Grown in Chapai",
          ],
          variety: "Fazli",
          slug: "fresh-fazli-mango",
        },
        {
          id: 5,
          name: "Khirshapat Mango Delight",
          description: "Popular Khirshapat mangoes, known for their smooth, melt-in-mouth texture.",
          price: 460,
          originalPrice: 540,
          images: [
            "/images/products/khirshapat-1.webp",
            "/images/products/khirshapat-2.webp",
            "/images/products/khirshapat-3.webp",
          ],
          rating: 4.9,
          reviews: 135,
          discount: "15% OFF",
          isNew: true,
          stock: 22,
          benefits: [
            "Silky Smooth Texture",
            "No Fibers",
            "Excellent for Desserts",
            "Bangladeshi Favorite",
          ],
          variety: "Khirshapat",
          slug: "khirshapat-mango-delight",
        },
        {
          id: 6,
          name: "Gopalbhog Mango Premium",
          description: "Early season Gopalbhog mangoes packed with flavor and fragrance.",
          price: 390,
          originalPrice: 460,
          images: [
            "/images/products/gopalbhog-1.webp",
            "/images/products/gopalbhog-2.webp",
            "/images/products/gopalbhog-3.webp",
          ],
          rating: 4.4,
          reviews: 89,
          discount: "15% OFF",
          isNew: false,
          stock: 16,
          benefits: [
            "Early Season Mango",
            "Smooth and Sweet",
            "Great Aroma",
            "No Artificial Ripening",
          ],
          variety: "Gopalbhog",
          slug: "gopalbhog-mango-premium",
        },
        {
          id: 7,
          name: "Organic Mohanbhog Mango",
          description: "Rare and delightful Mohanbhog mangoes from Rajshahi’s finest orchards.",
          price: 470,
          originalPrice: 560,
          images: [
            "/images/products/mohanbhog-1.webp",
            "/images/products/mohanbhog-2.webp",
            "/images/products/mohanbhog-3.webp",
          ],
          rating: 4.6,
          reviews: 67,
          discount: "16% OFF",
          isNew: true,
          stock: 12,
          benefits: [
            "Unique Flavor",
            "Rare Variety",
            "Naturally Grown",
            "Excellent for Gifting",
          ],
          variety: "Mohanbhog",
          slug: "organic-mohanbhog-mango",
        },
        {
          id: 8,
          name: "Organic Surjapuri Mango",
          description: "Surjapuri mangoes—sweet, juicy, and beloved for their light yellow skin.",
          price: 430,
          originalPrice: 500,
          images: [
            "/images/products/surjapuri-1.webp",
            "/images/products/surjapuri-2.webp",
            "/images/products/surjapuri-3.webp",
          ],
          rating: 4.3,
          reviews: 75,
          discount: "14% OFF",
          isNew: false,
          stock: 14,
          benefits: [
            "Distinctive Skin Tone",
            "High Sugar Content",
            "Satisfying Juiciness",
            "No Chemicals Used",
          ],
          variety: "Surjapuri",
          slug: "organic-surjapuri-mango",
        },
        {
          id: 9,
          name: "Kalibhog Mango Selection",
          description: "Aromatic Kalibhog mangoes, small in size but big on taste.",
          price: 390,
          originalPrice: 470,
          images: [
            "/images/products/kalibhog-1.webp",
            "/images/products/kalibhog-2.webp",
            "/images/products/kalibhog-3.webp",
          ],
          rating: 4.2,
          reviews: 60,
          discount: "17% OFF",
          isNew: true,
          stock: 19,
          benefits: [
            "Small But Flavorful",
            "Rich Scent",
            "Loved by Locals",
            "Fresh from Garden",
          ],
          variety: "Kalibhog",
          slug: "kalibhog-mango-selection",
        },
        {
          id: 10,
          name: "Organic Bombai Mango",
          description: "Traditional Bombai mangoes with a firm bite and nostalgic flavor.",
          price: 410,
          originalPrice: 490,
          images: [
            "/images/products/bombai-1.webp",
            "/images/products/bombai-2.webp",
            "/images/products/bombai-3.webp",
          ],
          rating: 4.1,
          reviews: 58,
          discount: "16% OFF",
          isNew: false,
          stock: 13,
          benefits: [
            "Firm Flesh",
            "Old School Taste",
            "Naturally Ripened",
            "Cultural Favorite",
          ],
          variety: "Bombai",
          slug: "organic-bombai-mango",
        },
        {
          id: 11,
          name: "Laxmanbhog Mango",
          description: "Laxmanbhog mangoes—deliciously sweet and soft, loved across generations.",
          price: 395,
          originalPrice: 475,
          images: [
            "/images/products/laxmanbhog-1.webp",
            "/images/products/laxmanbhog-2.webp",
            "/images/products/laxmanbhog-3.webp",
          ],
          rating: 4.3,
          reviews: 65,
          discount: "16% OFF",
          isNew: false,
          stock: 20,
          benefits: [
            "Rich Legacy",
            "Soft Texture",
            "Highly Juicy",
            "Farm Fresh",
          ],
          variety: "Laxmanbhog",
          slug: "laxmanbhog-mango",
        },
        {
          id: 12,
          name: "Organic Neelumbori Mango",
          description: "A rare gem—Neelumbori mangoes are fibrous, big, and perfectly pulpy.",
          price: 440,
          originalPrice: 530,
          images: [
            "/images/products/neelumbori-1.webp",
            "/images/products/neelumbori-2.webp",
            "/images/products/neelumbori-3.webp",
          ],
          rating: 4.0,
          reviews: 45,
          discount: "17% OFF",
          isNew: false,
          stock: 11,
          benefits: [
            "Rare Local Variety",
            "Large and Pulpy",
            "Perfect for Juicing",
            "Organic & Fresh",
          ],
          variety: "Neelumbori",
          slug: "organic-neelumbori-mango",
        },
      ];
  
    return Response.json(products);
  }